

import org.junit.Test; 
import org.junit.Before; 
import org.junit.After; 

/** 
* Bottle Tester. 
* 
* @author <Authors name> 
* @since <pre>nov 13, 2018</pre> 
* @version 1.0 
*/ 
public class BottleTest { 

@Before
public void before() throws Exception { 
} 

@After
public void after() throws Exception { 
} 

/** 
* 
* Method: getCurrentVolume() 
* 
*/ 
@Test
public void testGetCurrentVolume() throws Exception { 
//TODO: Test goes here... 
} 

/** 
* 
* Method: fillBottle() 
* 
*/ 
@Test
public void testFillBottle() throws Exception { 
//TODO: Test goes here... 
} 

/** 
* 
* Method: emptyBottle() 
* 
*/ 
@Test
public void testEmptyBottle() throws Exception { 
//TODO: Test goes here... 
} 

/** 
* 
* Method: getTransferredVolume(int volume) 
* 
*/ 
@Test
public void testGetTransferredVolume() throws Exception { 
//TODO: Test goes here... 
} 

/** 
* 
* Method: transferVolume(Bottle theOtherBottle) 
* 
*/ 
@Test
public void testTransferVolume() throws Exception { 
//TODO: Test goes here... 
} 

/** 
* 
* Method: isJustFilled() 
* 
*/ 
@Test
public void testIsJustFilled() throws Exception { 
//TODO: Test goes here... 
} 

/** 
* 
* Method: isJustEmptied() 
* 
*/ 
@Test
public void testIsJustEmptied() throws Exception { 
//TODO: Test goes here... 
} 

/** 
* 
* Method: isJustTransferred() 
* 
*/ 
@Test
public void testIsJustTransferred() throws Exception { 
//TODO: Test goes here... 
} 

/** 
* 
* Method: resetBottle() 
* 
*/ 
@Test
public void testResetBottle() throws Exception { 
//TODO: Test goes here... 
} 

/** 
* 
* Method: isJustGotTransferred() 
* 
*/ 
@Test
public void testIsJustGotTransferred() throws Exception { 
//TODO: Test goes here... 
} 

/** 
* 
* Method: getExceedVolume() 
* 
*/ 
@Test
public void testGetExceedVolume() throws Exception { 
//TODO: Test goes here... 
} 

/** 
* 
* Method: setExceedVolume(int exceedVolume) 
* 
*/ 
@Test
public void testSetExceedVolume() throws Exception { 
//TODO: Test goes here... 
} 

/** 
* 
* Method: getFullVolume() 
* 
*/ 
@Test
public void testGetFullVolume() throws Exception { 
//TODO: Test goes here... 
} 


} 
